### PR TITLE
Check that files with label extension are actually labels to avoid errors on floating XML files

### LINKED ISSUE #679: Validate throws internal error when coming across non-label XML in a target directory
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I validated a bundle that contains "floating", non-label XML files, I receive an internal error.

### 🕵️ Expected behavior

I expected validate to catch that this XML is not a PDS4 label, and throw a WARNING for the "floating" file, but not throw an internal error.

### 📜 To Reproduce

1. Touched new empty xml file `src/test/resources//github482/bundle2/data_spectra/foo.xml`
2. Copied https://asc-pds-messenger.s3.us-west-2.amazonaws.com/MSGRMDS_4001/EXTRAS/BROWSE/H10/MDIS_BDR_256PPD_H10SE2.PNG.aux.xml to `src/test/resources//github482/bundle2/data_spectra/`
3. Run validate:

```
$ validate-3.3.0-SNAPSHOT/bin/validate -t src/test/resources//github482/bundle2/bundle_kaguya_derived.xml -R pds4.bundle


net.sf.saxon.trans.UncheckedXPathException: Error reported by XML parser processing file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github482/bundle2/data_spectra/foo.xml: Premature end of file.
	at net.sf.saxon.lib.DelegatingErrorListener.fatalError(DelegatingErrorListener.java:51)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:451)
	at net.sf.saxon.event.Sender.send(Sender.java:141)
	at net.sf.saxon.Configuration.buildDocumentTree(Configuration.java:4236)
	at net.sf.saxon.Configuration.buildDocument(Configuration.java:4319)
	at gov.nasa.pds.tools.util.LabelParser.parse(LabelParser.java:41)
	at gov.nasa.pds.tools.validate.TargetExaminer.getTargetContent(TargetExaminer.java:184)
	at gov.nasa.pds.tools.validate.AggregateManager.selectMatchingReferenceFromCollection(AggregateManager.java:206)
	at gov.nasa.pds.tools.validate.AggregateManager.findCollectionWithMatchingReference(AggregateManager.java:340)
	at gov.nasa.pds.tools.validate.AggregateManager.buildCollectionIgnoreList(AggregateManager.java:547)
	at gov.nasa.pds.tools.validate.AggregateManager.makeException(AggregateManager.java:853)
	at gov.nasa.pds.tools.label.LocationValidator.validate(LocationValidator.java:219)
	at gov.nasa.pds.validate.ValidateLauncher.doValidation(ValidateLauncher.java:1445)
	at gov.nasa.pds.validate.ValidateLauncher.processMain(ValidateLauncher.java:1731)
	at gov.nasa.pds.validate.ValidateLauncher.main(ValidateLauncher.java:1780)
net.sf.saxon.trans.UncheckedXPathException: Error reported by XML parser processing file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github482/bundle2/data_spectra/foo.xml: Premature end of file.
	at net.sf.saxon.lib.DelegatingErrorListener.fatalError(DelegatingErrorListener.java:51)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:451)
	at net.sf.saxon.event.Sender.send(Sender.java:141)
	at net.sf.saxon.Configuration.buildDocumentTree(Configuration.java:4236)
	at net.sf.saxon.Configuration.buildDocument(Configuration.java:4319)
	at gov.nasa.pds.tools.util.LabelParser.parse(LabelParser.java:41)
	at gov.nasa.pds.tools.validate.TargetExaminer.tagMatches(TargetExaminer.java:130)
	at gov.nasa.pds.tools.validate.TargetExaminer.isTargetCollectionType(TargetExaminer.java:93)
	at gov.nasa.pds.tools.validate.TargetExaminer.isTargetCollectionType(TargetExaminer.java:81)
	at gov.nasa.pds.tools.validate.AggregateManager.findOtherCollectionFiles(AggregateManager.java:730)
	at gov.nasa.pds.tools.validate.AggregateManager.buildCollectionIgnoreList(AggregateManager.java:562)
	at gov.nasa.pds.tools.validate.AggregateManager.makeException(AggregateManager.java:853)
	at gov.nasa.pds.tools.label.LocationValidator.validate(LocationValidator.java:219)
	at gov.nasa.pds.validate.ValidateLauncher.doValidation(ValidateLauncher.java:1445)
	at gov.nasa.pds.validate.ValidateLauncher.processMain(ValidateLauncher.java:1731)
	at gov.nasa.pds.validate.ValidateLauncher.main(ValidateLauncher.java:1780)

PDS Validate Tool Report

Configuration:
   Version                       3.3.0-SNAPSHOT
   Date                          2023-08-16T16:39:40Z

Parameters:
   Targets                       [file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github482/bundle2/bundle_kaguya_derived.xml]
   Rule Type                     pds4.bundle
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Allow Unlabeled Files         false
   Max Errors                    100000
   Registered Contexts File      /Users/jpadams/proj/pds/pdsen/workspace/validate/validate-3.3.0-SNAPSHOT/resources/registered_context_products.json



Product Level Validation Results

  PASS: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github482/bundle2/bundle_kaguya_derived.xml
        1 product validation(s) completed
Fatal error: [node=null,object=null,url=file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github482/bundle2/data_spectra/MDIS_BDR_256PPD_H10SE2.PNG.aux.xml,line=1,col=13,offset=-1]: unexpected element (uri:"", local:"PAMDataset"). Expected elements are <{http://pds.nasa.gov/pds4/disp/v1}Color_Display_Settings>,<{http://pds.nasa.gov/pds4/disp/v1}Display_Direction>,<{http://pds.nasa.gov/pds4/disp/v1}Display_Settings>,<{http://pds.nasa.gov/pds4/pds/v1}External_Reference>,<{http://pds.nasa.gov/pds4/pds/v1}Ingest_LDD>,<{http://pds.nasa.gov/pds4/pds/v1}Internal_Reference>,<{http://pds.nasa.gov/pds4/pds/v1}Local_Internal_Reference>,<{http://pds.nasa.gov/pds4/disp/v1}Movie_Display_Settings>,<{http://pds.nasa.gov/pds4/pds/v1}Product_AIP>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Ancillary>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Attribute_Definition>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Browse>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Bundle>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Class_Definition>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Collection>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Context>,<{http://pds.nasa.gov/pds4/pds/v1}Product_DIP>,<{http://pds.nasa.gov/pds4/pds/v1}Product_DIP_Deep_Archive>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Data_Set_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Document>,<{http://pds.nasa.gov/pds4/pds/v1}Product_File_Repository>,<{http://pds.nasa.gov/pds4/pds/v1}Product_File_Text>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Instrument_Host_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Instrument_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Metadata_Supplemental>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Mission_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Native>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Observational>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Proxy_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_SIP>,<{http://pds.nasa.gov/pds4/pds/v1}Product_SIP_Deep_Archive>,<{http://pds.nasa.gov/pds4/pds/v1}Product_SPICE_Kernel>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Service>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Software>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Subscription_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Target_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Thumbnail>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Update>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Volume_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Volume_Set_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_XML_Schema>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Zipped>,<{http://pds.nasa.gov/pds4/pds/v1}local_identifier>,<{http://pds.nasa.gov/pds4/pds/v1}logical_identifier>
Fatal error: [node=null,object=null,url=file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github482/bundle2/data_spectra/MDIS_BDR_256PPD_H10SE2.PNG.aux.xml,line=1,col=13,offset=-1]: unexpected element (uri:"", local:"PAMDataset"). Expected elements are <{http://pds.nasa.gov/pds4/disp/v1}Color_Display_Settings>,<{http://pds.nasa.gov/pds4/disp/v1}Display_Direction>,<{http://pds.nasa.gov/pds4/disp/v1}Display_Settings>,<{http://pds.nasa.gov/pds4/pds/v1}External_Reference>,<{http://pds.nasa.gov/pds4/pds/v1}Ingest_LDD>,<{http://pds.nasa.gov/pds4/pds/v1}Internal_Reference>,<{http://pds.nasa.gov/pds4/pds/v1}Local_Internal_Reference>,<{http://pds.nasa.gov/pds4/disp/v1}Movie_Display_Settings>,<{http://pds.nasa.gov/pds4/pds/v1}Product_AIP>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Ancillary>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Attribute_Definition>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Browse>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Bundle>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Class_Definition>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Collection>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Context>,<{http://pds.nasa.gov/pds4/pds/v1}Product_DIP>,<{http://pds.nasa.gov/pds4/pds/v1}Product_DIP_Deep_Archive>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Data_Set_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Document>,<{http://pds.nasa.gov/pds4/pds/v1}Product_File_Repository>,<{http://pds.nasa.gov/pds4/pds/v1}Product_File_Text>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Instrument_Host_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Instrument_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Metadata_Supplemental>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Mission_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Native>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Observational>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Proxy_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_SIP>,<{http://pds.nasa.gov/pds4/pds/v1}Product_SIP_Deep_Archive>,<{http://pds.nasa.gov/pds4/pds/v1}Product_SPICE_Kernel>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Service>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Software>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Subscription_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Target_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Thumbnail>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Update>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Volume_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Volume_Set_PDS3>,<{http://pds.nasa.gov/pds4/pds/v1}Product_XML_Schema>,<{http://pds.nasa.gov/pds4/pds/v1}Product_Zipped>,<{http://pds.nasa.gov/pds4/pds/v1}local_identifier>,<{http://pds.nasa.gov/pds4/pds/v1}logical_identifier>

  FAIL: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github482/bundle2/data_spectra/MDIS_BDR_256PPD_H10SE2.PNG.aux.xml
      FATAL_ERROR  [error.label.schema]   No schema(s) found in the label.
      WARNING  [warning.label.missing_schematron_spec]   No schematrons specified in the label
      WARNING  [warning.label.schema]   Cannot check versioning because no Schema given.
      ERROR  [error.label.schema]   line 1, 13: cvc-elt.1.a: Cannot find the declaration of element 'PAMDataset'.
      ERROR  [error.validation.internal_error]   Uncaught exception while validating: No schema(s) specified in the label.
        2 product validation(s) completed
Fatal error: [node=null,object=null,url=null,line=-1,col=-1,offset=-1]: Premature end of file.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:64)
	at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
	at gov.nasa.pds.tools.validate.rule.pds4.LabelInFolderRule$1.run(LabelInFolderRule.java:147)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: net.sf.saxon.trans.UncheckedXPathException: Error reported by XML parser processing file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github482/bundle2/data_spectra/foo.xml: Premature end of file.
	at net.sf.saxon.lib.DelegatingErrorListener.fatalError(DelegatingErrorListener.java:51)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:451)
	at net.sf.saxon.event.Sender.send(Sender.java:141)
	at net.sf.saxon.Configuration.buildDocumentTree(Configuration.java:4236)
	at net.sf.saxon.Configuration.buildDocument(Configuration.java:4319)
	at gov.nasa.pds.tools.util.XMLExtractor.<init>(XMLExtractor.java:88)
	at gov.nasa.pds.tools.label.LabelValidator.checkSchemaSchematronVersions(LabelValidator.java:381)
	at gov.nasa.pds.tools.label.LabelValidator.parseAndValidate(LabelValidator.java:480)
	at gov.nasa.pds.tools.validate.rule.pds4.LabelValidationRule.validateLabel(LabelValidationRule.java:316)
	... 12 more

  PASS: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github482/bundle2/data_spectra/kgrs_calibrated_spectra_per1.xml
        3 product validation(s) completed

  PASS: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github482/bundle2/data_spectra/spectra_data_collection_inventory.xml
        4 product validation(s) completed

  FAIL: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github482/bundle2/data_spectra/
      ERROR  [error.validation.internal_error]   Uncaught exception while validating: Index 0 out of bounds for length 0


PDS4 Bundle Level Validation Results

  FAIL: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github482/bundle2/
      ERROR  [error.validation.internal_error]   Uncaught exception while validating: Index 0 out of bounds for length 0

  FAIL: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github482/bundle2/data_spectra/foo.xml
      ERROR  [error.validation.internal_error]   Uncaught exception while validating: null
      WARNING  [warning.file.not_referenced_in_label]   File is not referenced by any label
        1 integrity check(s) completed

  PASS: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github482/bundle2/data_spectra/spectra_data_collection_inventory.xml
        2 integrity check(s) completed

  PASS: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github482/bundle2/bundle_kaguya_derived.xml
        3 integrity check(s) completed

  PASS: file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github482/bundle2/data_spectra/kgrs_calibrated_spectra_per1.xml
        4 integrity check(s) completed

  PASS: gov.nasa.pds.validate.ValidateLauncher
      WARNING  [warning.integrity.pds4_version_mismatch]   Multiple versions (2) of Information Model (IM) found in this run: [1.15.0.0, null] for rule pds4.bundle for bundle file:/Users/jpadams/proj/pds/pdsen/workspace/validate/src/test/resources/github482/bundle2/bundle_kaguya_derived.xml
        5 integrity check(s) completed

Summary:

  6 error(s)
  4 warning(s)

  Product Validation Summary:
    3          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    4          check(s) passed
    1          check(s) failed
    0          check(s) skipped

  Message Types:
    4            error.validation.internal_error
    2            error.label.schema
    1            warning.integrity.pds4_version_mismatch
    1            warning.label.schema
    1            warning.label.missing_schematron_spec
    1            warning.file.not_referenced_in_label

End of Report
Completed execution in 4476 ms
```

### 🖥 Environment Info

MacBook Ventura 13.5

### 📚 Version of Software Used

v3.3.0-SNAPSHOT (as of 8/16)

### 🩺 Test Data / Additional context

_No response_

### 🦄 Related requirements

_No response_

### ⚙️ Engineering Details

_No response_

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Add a check that files that have the label extension really are labels and remove them from the target list if they are not preventing lots of SAX parsing exceptions. Files that are "floating" like this show up as un-referenced warnings by the bundle or collection. If given as the target, it will still blow up making it obvious to the user.

## ⚙️ Test Data and/or Report
See automate unit tests below (specifically 482).

## ♻️ Related Issues
Closes #679

### CODE REVIEW

File: src/main/java/gov/nasa/pds/tools/validate/TargetExaminer.java [hunk 1]
```diff
@@ -221,4 +221,37 @@ public static ArrayList<String> getTargetContent(URL url, String nodeCheck, Stri
...
+      InputSource source = Utility.getInputSourceByURL(url);
+      SAXSource saxSource = new SAXSource(source);
+      saxSource.setSystemId(url.toString());
+      DocumentInfo docInfo = LabelParser.parse(saxSource); // Parses a label.
+      @SuppressWarnings("unused")
+      List<TinyNodeImpl> xmlModels = new ArrayList<>();
+      XMLExtractor extractor = new XMLExtractor(docInfo);
+      xmlModels = extractor.getNodesFromDoc("logical_identifier");
+      return true;
+    } catch (Throwable t) {
```
Comment (nutjob4life) [inline src/main/java/gov/nasa/pds/tools/validate/TargetExaminer.java:235]: I'd prefer to see
```java
} catch (RuntimeException ex) {
  throw ex;
} catch (Exception ex) {
  return false;
}
```
otherwise serious environmental situations like `OutOfMemoryError` will be treated as the target not being a label when it should abort the program. (This is all due to the [defect in the way the Java exception hierarchy was defined from the beginning](https://github.com/NASA-PDS/nasa-pds.github.io/wiki/Java-Exceptions-Gotcha).)

**Review by nutjob4life — CHANGES_REQUESTED** [review]

File: src/main/java/gov/nasa/pds/tools/validate/TargetExaminer.java (hunk 1 above)
Comment (al-niessner) [reply src/main/java/gov/nasa/pds/tools/validate/TargetExaminer.java:235]: The errors that we have to catch are runtime errors unfortunately and not always predictable -- cannot enumerate them a priori. I agree that hiding out of memory errors is bad, but it is not likely that this would be the sole function that caused it since this is not the first function to read the file.  Nothing is done with the data that is read and all objects allocated here are disposed of immediately, well at the GC's leisure, making the risk of catching throwable here very minimal.

Comment (nutjob4life) [reply src/main/java/gov/nasa/pds/tools/validate/TargetExaminer.java:235]: Wait … so the functions `getInputSourceByURL`, `parse`, and/or `getNodesFromDoc` actually throw `RuntimeException`s on purpose instead of using some app-specific subclass of `Exception`?

Comment (al-niessner) [reply src/main/java/gov/nasa/pds/tools/validate/TargetExaminer.java:235]: Yes plus extensions of exception and not sure why some are and are not extensions of runtime - they do not throw runtime but their extensions of runtime. That way you do not need to explicitly catch exceptions since we never use a URL that would cause one. Not my favorite libraries nor is catching exceptions my favorite way to test that something is valid - would rather have a library like xmllint say true/false on a comparison of the file and the schema. The schema is not fixed and part of the file being read so how do you read the file to get the schema to do the check, catch throwable since any exception can occur during the process. I would even take a JAXB mapping that condensed the exceptions down to a one or two rather but it requires generating code from schema that is not stationary.

If it would make you happier, could catch out of memory first, and raise again rather than null handler in this silly do nothing function. Could just make it exception instead of throwable and deal with the odd cases of runtime when they appear too.

Again, do not really care because the risk of this function masking some deep problem is really, really small. I do get the panic over violating best practices though.

Comment (nutjob4life) [reply src/main/java/gov/nasa/pds/tools/validate/TargetExaminer.java:235]: Nah … I mean … there are just _so many_ `RuntimeException`s … everything from `AnnotationTypeMismatchException` to `ConcurrentModificationException` to `IllegalStateException` to `SecurityException` to `SystemException`.

It's all low-level stuff and not the kind of thing you usually want to mix with application logic … I blame Steve Hughes for conflating the two kinds of exceptions in the first place 😆

Anyway, leave it catching `Throwable` and call this resolved.

Just my mind is still doing this: 🤯😂

**Review by nutjob4life — APPROVED** [review]

**Review by jordanpadams — APPROVED** [review]
