### PR TITLE
Update content validation for windows and fix tests

### LINKED ISSUE #503: validate passes confusing message to the command window
## 🐛 Describe the bug
For every data file (*.tab), in the command window validate prints:
"java.io.FileNotFoundException: null\uvis_euv_2005_159_solar_time_series_ingress.tab (The system cannot find the path specified)"

However, it does complete content validation on every file. I forced an error into the file mentioned above, and validate found it.
## 📜 To Reproduce

I'm running validate from the command line on a windows 10 machine with JRE version 1.8.0_311

My command line entry is:
validate 2022-05-19-becker-solar-occ\cdap2018_becker_saturn_ring_particles_V9 -C .\catalog.xml -R pds4.bundle -v 2 -r becker-bundle_V9-0n.log

I use a catalog file located in the directory from which I am running validate.

## 🕵️ Expected behavior

Not get the message

## 📚 Version of Software Used

2.1.4
## 🩺 Test Data / Additional context

Let me know if you want some.
##  🏞Screenshots

[validate-print-screen.txt](https://github.com/NASA-PDS/validate/files/8732231/validate-print-screen.txt)

## 🖥 System Info

---

### LINKED ISSUE #507: validate having issues checking some file content on windows
## 🐛 Describe the bug

From user:
> I was test running version 2.2.0 of validate to see if it fixed the problem I previously reported. It seems to be working. But I am getting lots of messages on my terminal that I don’t understand. A short capture of the terminal is listed below.
 
```
Q:\stage\lunar\aamigration\diviner_rdr>Q:\stage\tools\pds4_validate\validate-2.2.0\bin\validate -v2 -C catalog_v02.xml -
R pds4.bundle -r xtest_con.txt -t Q:\stage\lunar\aamigration\diviner_rdr\bundle_test >xlog.txt
java.io.FileNotFoundException: null\201401112330_rdr.tab (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.getFirstLineLength(TableDataContentValid
ationRule.java:614)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.isTableLineOriented(TableDataContentVali
dationRule.java:656)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.validateTableDataContents(TableDataConte
ntValidationRule.java:1111)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:71)
        at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
        at gov.nasa.pds.tools.validate.rule.pds4.LabelInFolderRule$1.run(LabelInFolderRule.java:151)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.io.FileNotFoundException: null\201401111410_rdr.tab (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.getFirstLineLength(TableDataContentValid
ationRule.java:614)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.isTableLineOriented(TableDataContentVali
dationRule.java:656)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.validateTableDataContents(TableDataConte
ntValidationRule.java:1111)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:71)
        at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
        at gov.nasa.pds.tools.validate.rule.pds4.LabelInFolderRule$1.run(LabelInFolderRule.java:151)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.io.FileNotFoundException: null\201401111950_rdr.tab (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.getFirstLineLength(TableDataContentValid
ationRule.java:614)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.isTableLineOriented(TableDataContentVali
dationRule.java:656)
        at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.validateTableDataContents(TableDataConte
ntValidationRule.java:1111)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:71)
        at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
        at gov.nasa.pds.tools.validate.rule.pds4.LabelInFolderRule$1.run(LabelInFolderRule.java:151)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

## 🕵️ Expected behavior

Reads in file successfully

## 📚 Version of Software Used

2.2.0

## 🩺 Test Data / Additional context

Any table data on windows

## 🖥 System Info
Windows

---

## 🦄 Related requirements
Same as https://github.com/NASA-PDS/validate/issues/503

### PR DESCRIPTION
**Pull request by jordanpadams**
## 🗒️ Summary
Brief summary of changes if not sufficiently described by commit messages.

## ⚙️ Test Data and/or Report
One of the following should be included here:
* Reference to regression test included in code (preferred wherever reasonable)
* Attach test data here + outputs of tests

## ♻️ Related Issues

Resolves #507
Resolves #503

### CODE REVIEW

File: src/main/java/gov/nasa/pds/tools/util/ReferentialIntegrityUtil.java [hunk 1]
```diff
@@ -509,7 +509,7 @@ private static void crawlParentForBundleLabel(URL crawlTarget) {
     List<Target> children = new ArrayList<Target>();
     try {
       if (getContext().getCrawler() != null) {
```
Comment (tloubrieu-jpl) [inline src/main/java/gov/nasa/pds/tools/util/ReferentialIntegrityUtil.java:511]: Minor comment, you could assign and test at the same time:

if ((Crawler crawler = getContext().getCrawler()) != null) {
    crawler.crawl(...

To be more DRY, but that is definitelly not a big deal.

**Review by tloubrieu-jpl — APPROVED** [review]
Does that pull request helps with the issues Zareh is experiencing when running the tests on windows ? He showed me an issue he had last Tuesday.

Thanks,

Thomas

File: src/main/java/gov/nasa/pds/tools/util/ReferentialIntegrityUtil.java (hunk 1 above)
Comment (jordanpadams) [reply src/main/java/gov/nasa/pds/tools/util/ReferentialIntegrityUtil.java:511]: thanks @tloubrieu-jpl this entire codebase needs to be scrubbed
