### PR TITLE
Read the Table_Character correctly to read to the end of the record b…

### LINKED ISSUE #325: Validate Incorrectly Throws Error When Embedded Field_Character Contains <CR><LF>
## 🐛 Describe the bug
I have Table_Character files with long records.  Carriage-Return Line-Feed pairs have been embedded within the records to facilitate display; but the original (long) record length has been retained in the label.  Validate finds the embedded delimiter pairs, claims my records are too short, and throws errors.  
A prohibition on embedded Line-Feed and Carriage-Return characters was approved for Field_Delimited in CCB-181; a broader prohibition on non-printing control characters in Field_Character was proposed in CCB-196, but it was rejected by DDWG.  That presumably means Carriage-Return Line-Feed pairs may appear in embedded Field_Character so long as the records are correctly delimited by Carriage-Return Line-Feed.
Validate should return errors if character records are incorrectly delimited; it should not return errors if delimiter pairs are found internal to records.

## 📜 To Reproduce
1. Run validate on the attached crs009x.{tab, xml} product
2. See error report (crs009x_report.txt)

## 🕵️ Expected behavior
crs009x.{tab, xml} should pass.

## 📚 Version of Software Used
validate 1.24.0

## 🩺 Test Data / Additional context
[crs009x.tab.gz](https://github.com/NASA-PDS/validate/files/6288046/crs009x.tab.gz)
[crs009x.xml.gz](https://github.com/NASA-PDS/validate/files/6288047/crs009x.xml.gz)
[crs009x_report.txt](https://github.com/NASA-PDS/validate/files/6288041/crs009x_report.txt)

##  🏞Screenshots
N/A

## 🖥 System Info
 - OS: Mac OSX 11.1
 - Browser: Safari 14.0.2
 - Version

---

** :unicorn: Applicable requirements**

### PR DESCRIPTION
**Pull request by qchaupds**
…ased on record length instead of the normal <CR><LF> and null pointer should not show up.

Closes NASA-PDS/validate#325, NASA-PDS/validate#335

This pull request resolves two issues: Read the Table_Character correctly and corrected the null pointer when checking for a command line parameter.

Tested in DEV for #325
Previously would result in ERROR because it was reading the file line by line, which causes the record to end prematurely

% validate -R pds4.label --skip-context-validation -r report_github325_label_valid.json -s json -t src/test/resources/github325/crs009x.xml

Tested in DEV for #335
Three different ways to process a target, none should throw an exception.

% validate -R pds4.label  --skip-context-validation -r report_github335_as_label.json   -s json -t src/test/resources/github335/minimal_test_product.xml 
% validate   --skip-context-validation -r report_github335_as_target.json   -s json -t src/test/resources/github335/*.xml 
% validate   --skip-context-validation -r report_github335_as_dir.json   -s json -t src/test/resources/github335

### CODE REVIEW

File: src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java [hunk 1]
```diff
@@ -166,6 +168,339 @@ public boolean isApplicable(String location) {
...
+      } catch (IOException e) {
+          LOG.error("Cannot read from file {}",dataFile);
+          e.printStackTrace();
+      }
+      LOG.debug("getFirstLineLength:dataFile,firstLineLength {},{}",dataFile,firstLineLength);
+      return(firstLineLength);
+  }
+
+  private boolean isTableLineOriented(Object table, URL dataFile) {
+      // Given a text table object, determine if it a line oriented table or not.  A line-oriented table contains some record delimiter and optional record_length.
```
Comment (jordanpadams) [inline src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java]: @qchaupds can we add this as a javadoc?

```java
/**
 * Given a text table object, determine if it a line oriented table or not.  A l ...
 **/
```

File: src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java [hunk 2]
```diff
@@ -166,6 +168,339 @@ public boolean isApplicable(String location) {
...
+                  dataFile,
+                  tableIndex,
+                  -1);
+      } 
+      LOG.debug("validateTableContentLineWise:DONE_VALIDATING");
+  }
+
+
+  private long getFirstLineLength(URL dataFile) {
+      // Take a peek and read the first line from the file and retrieve the line length.
```
Comment (jordanpadams) [inline src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java]: @qchaupds can we add this as a javadoc?

```java
/**
 * Given a text table object, determine if it a line oriented table or not.  A l ...
 **/
```

File: src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java [hunk 3]
```diff
@@ -166,6 +168,339 @@ public boolean isApplicable(String location) {
...
+                          + "(max " + recordMaxLength
+                          + ", got " + line.length() + ").",
+                      dataFile,
+                      tableIndex,
+                      reader.getCurrentRow());
+              }
+          }
+          // Need to manually parse the line if we're past the defined
+          // number of records. The PDS4-Tools library won't let us
+          // read past the defined number of records.
```
Comment (jordanpadams) [inline src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java:372]: @qchaupds if there is data beyond the number of records defined, this can be considered a "footer" for the data and we should not assume anything about this data and/or manually read the data.

we should just throw a warning that there is more data than expected based upon the number of rows (I thought we already did this?).

this could be used for calculating the file size, but we should not do any more validation with the assumption these are actual rows of the table

Comment (jordanpadams) [reply src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java:372]: looking at the code below, i may be misunderstanding what is happening here, but we shouldn't be checking any of the data in the "footer" of the data. we should just throw a warning and use the extra info to calculate the file size

File: src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java (hunk 1 above)
Comment (qchaupds) [reply src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java]: Done now and pushed to github.

File: src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java (hunk 2 above)
Comment (qchaupds) [reply src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java]: Done now and pushed to github.

File: src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java (hunk 3 above)
Comment (qchaupds) [reply src/main/java/gov/nasa/pds/tools/validate/rule/pds4/TableDataContentValidationRule.java:372]: The code you are asking about is extracted AS-IS from a very large function.   Perhaps we can look at this in a separate ticket.

**Review by jordanpadams — CHANGES_REQUESTED** [review]
@qchaupds looks like we are missing the test data

**Comment by qchaupds** [comment]
My bad @jordanpadams .  Both resources are just checked in:

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 116 % git commit -m "Add missing test resources"
[#325_335 997f9ff] Add missing test resources
 Committer: Qui T Chau <qchau@pds-dev3.jpl.nasa.gov>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly:

    git config --global user.name "Your Name"
    git config --global user.email you@example.com

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 5 files changed, 476 insertions(+)
 create mode 100644 src/test/resources/github325/crs009x.tab
 create mode 100644 src/test/resources/github325/crs009x.xml
 create mode 100644 src/test/resources/github335/minimal_test_product.csv
 create mode 100644 src/test/resources/github335/minimal_test_product.tab
 create mode 100644 src/test/resources/github335/minimal_test_product.xml
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 117 % git push
Counting objects: 16, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (12/12), done.
Writing objects: 100% (12/12), 4.29 KiB | 0 bytes/s, done.
Total 12 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To git@github.com:NASA-PDS/validate.git
   89e36ca..997f9ff  #325_335 -> #325_335

**Comment by jordanpadams** [comment]
per last commit, also resolves #336
