### PR TITLE
Suggested fix for NPE on label object. ...

### LINKED ISSUE #545: Validate 2.4.0/3.0.0 fail with NPE/internal error on certain test cases
## 🐛 Describe the bug identified during I&T
Execute `validate -t testdata/badtype.xml` against the linked dataset used to test pds4-im#499. This will yield both an exception and an internal error. (See attached output, Also, please note an earlier SNAPSHOT of Validate 2.4.0 did not yield this error but the current releases do.)

This error only manifests on this test case so far as others currently appear to not yield the error.

## 🥼 Related Test Case(s)
[pds4-im#499](https://github.com/NASA-PDS/pds4-information-model/issues/499)

## 🔁 : Related issues
These may not be proximately related, but the refactoring preceded the report:
https://github.com/NASA-PDS/validate/issues/425
https://github.com/NASA-PDS/validate/issues/537

---

## ➕ Additional Details
Versions: Java 11, Validate 3.0.0 and Validate 2.4.0
Also, both test commands yield errors:
`validate -t baddata.xml`
`validate -t shouldpass.xml`

### 📜 To Reproduce
Download dataset:
Execute `validate -t baddata.xml` to view error.
Execute `validate -t shouldpass.xml` to view error.

### 🕵️ Expected behavior
No NPE, no internal error. Validation should proceed to notify user of errors/warnings or pass product.

### 📚 Version of Software Used
Validate 2.4.0
Validate 3.0.0

### 🩺 Test Data / Additional context
https://github.com/NASA-PDS/pds4-information-model/files/9952397/testdata.zip

###  🏞Screenshots
Execution log: 
[validate-2.4.0-3.0.0-badtype-fail.txt](https://github.com/NASA-PDS/validate/files/9952438/validate-2.4.0-3.0.0-badtype-fail.txt)

### 🖥 System Info
 - OS: Mac OS X 11.7.1
 - java 11.0.3 2019-04-16 LTS
 - Validate 2.4.0 or 3.0.0
 - GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)

---

### PR DESCRIPTION
**Pull request by jpl-jengelke**
## 🗒️ Summary
Described in commit message, e.g. fix for null object NPE.

Closes NASA-PDS/validate#545 

An attempt is made to execute the `close()` method on a non-existent object. 

This is the proximate fix for the NPE but it does not address why the `Label` object does not exist. It will close the ticket but we may want to leave it open for further analysis. 

## ⚙️ Test Data and/or Report
N/A

## ♻️ Related Issues
Fixes: 
- https://github.com/NASA-PDS/validate/issues/545

### CODE REVIEW

**Review by jimmie — APPROVED** [review]

File: src/main/java/gov/nasa/pds/tools/validate/rule/pds4/DataDefinitionAndContentValidationRule.java [hunk 1]
```diff
@@ -114,7 +114,8 @@ public void validate() throws MalformedURLException, URISyntaxException {
           getTarget(), objectCounter, -1));
       // e.printStackTrace();
     } finally {
-      label.close();
+        if(nonNull(label))
```
Comment (nutjob4life) [inline src/main/java/gov/nasa/pds/tools/validate/rule/pds4/DataDefinitionAndContentValidationRule.java:117]: This doesn't compile for me (jdk1.8).

Need to add `import java.util.Objects;` to the top of the file and change the conditional to:
```java
if (Objects.nonNull(label))
```

**Review by nutjob4life — CHANGES_REQUESTED** [review]
Close! But not quite there yet.

File: src/main/java/gov/nasa/pds/tools/validate/rule/pds4/DataDefinitionAndContentValidationRule.java (hunk 1 above)
Comment (jimmie) [reply src/main/java/gov/nasa/pds/tools/validate/rule/pds4/DataDefinitionAndContentValidationRule.java:117]: My bad, @nutjob4life - thanks for the saving catch

Comment (jpl-jengelke) [reply src/main/java/gov/nasa/pds/tools/validate/rule/pds4/DataDefinitionAndContentValidationRule.java:117]: I thought we were supposed to use JDK 11 or 15 or something, according to docs. Nonetheless, yes, it was missing the import.
