### PR TITLE
Refactoring to fix auto detected coding issues

### LINKED ISSUE #698: Investigate and Fix code scanning alert for potential improvements
Tracking issue for:
- [x] https://github.com/NASA-PDS/validate/security/code-scanning/316
- [x] https://github.com/NASA-PDS/validate/security/code-scanning/315
- [ ] ~https://github.com/NASA-PDS/validate/security/code-scanning/12~ moved [here](https://github.com/NASA-PDS/validate/issues/708)
- [ ] ~https://github.com/NASA-PDS/validate/security/code-scanning/13~ moved [here](https://github.com/NASA-PDS/validate/issues/708)
- [x] https://github.com/NASA-PDS/validate/security/code-scanning/119
- [x] https://github.com/NASA-PDS/validate/security/code-scanning/120
- [x] https://github.com/NASA-PDS/validate/security/code-scanning/117
- [x] https://github.com/NASA-PDS/validate/security/code-scanning/118
- [x] https://github.com/NASA-PDS/validate/security/code-scanning/116
- [x] https://github.com/NASA-PDS/validate/security/code-scanning/115
- [x] https://github.com/NASA-PDS/validate/security/code-scanning/125
- [x] https://github.com/NASA-PDS/validate/security/code-scanning/119
- [x] https://github.com/NASA-PDS/validate/security/code-scanning/123
- [x] https://github.com/NASA-PDS/validate/security/code-scanning/122
- [x] https://github.com/NASA-PDS/validate/security/code-scanning/121

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Fixed issues raised by static analysis.

## ⚙️ Test Data and/or Report
No compiler errors and successful automated unit tests (see below)

## ♻️ Related Issues
Closes https://github.com/NASA-PDS/validate/security/code-scanning/316
Closes https://github.com/NASA-PDS/validate/security/code-scanning/315
Closes https://github.com/NASA-PDS/validate/security/code-scanning/119
Closes https://github.com/NASA-PDS/validate/security/code-scanning/120
Closes https://github.com/NASA-PDS/validate/security/code-scanning/117
Closes https://github.com/NASA-PDS/validate/security/code-scanning/118
Closes https://github.com/NASA-PDS/validate/security/code-scanning/116
Closes https://github.com/NASA-PDS/validate/security/code-scanning/115
Closes https://github.com/NASA-PDS/validate/security/code-scanning/125
Closes https://github.com/NASA-PDS/validate/security/code-scanning/119
Closes https://github.com/NASA-PDS/validate/security/code-scanning/123
Closes https://github.com/NASA-PDS/validate/security/code-scanning/122
Closes https://github.com/NASA-PDS/validate/security/code-scanning/121 

Closes #698

### CODE REVIEW

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life @tloubrieu-jpl 

Did not fix the two regex complaints because these are cut-n-paste from the PDS requirements (schema, schematron, and/or docs). Hence changing the may cause subtle differences that could cause bigger problems with the customer base.

File: src/main/java/gov/nasa/pds/tools/util/ContextProductReference.java [hunk 1]
```diff
@@ -109,23 +109,30 @@ public String toString() {
...
-    // lidvid.getType());
-
-    // Compare Lid and/or version only
-    if (this.lid.equalsIgnoreCase(lidvid.getLid())) {
-      if (this.hasVersion) {
-        if (lidvid.hasVersion() && this.version.equals(lidvid.getVersion())) {
+    if (o instanceof ContextProductReference) {
+      ContextProductReference lidvid = (ContextProductReference) o;
+
+      // if(lidvid.getName().equals("N/A"))
```
Comment (nutjob4life) [inline src/main/java/gov/nasa/pds/tools/util/ContextProductReference.java]: Maybe just delete this? If it's needed, add a comment saying why it's commented-out, to help reduce doubt in future readers of this code.

File: src/main/java/gov/nasa/pds/web/ui/utils/TabularData.java [hunk 2]
```diff
@@ -74,12 +74,13 @@ public TabularData(URL fileUrl, List<ColumnInfo> columnInfos, long startByte,
         final BufferedReader br = new BufferedReader(new InputStreamReader(fileUrl.openStream()));
         String currLine = null;
         int lineNumber = 1;
-
+        long llineNumber = 1;
```
Comment (nutjob4life) [inline src/main/java/gov/nasa/pds/web/ui/utils/TabularData.java:77]: Can we delete `int lineNumber = 1` and all the increments of it later on `lineNumber++`? It looks like `llineNumber` replaces it? 🤷

**Review by nutjob4life — CHANGES_REQUESTED** [review]

File: src/main/java/gov/nasa/pds/web/ui/utils/TabularData.java (hunk 2 above)
Comment (jordanpadams) [reply src/main/java/gov/nasa/pds/web/ui/utils/TabularData.java:77]: @al-niessner ☝️

Comment (al-niessner) [reply src/main/java/gov/nasa/pds/web/ui/utils/TabularData.java:77]: Primitives are so annoying. No, cannot delete the int. If we go with long, then have to convert long to int for the call a couple of lines down within the loop that has an int in its constructor. So, either two variable (bleh) or cast between in int/long in a loop. Personally I would go with the latter but the static analysis seems to dislike that idea. Changing the constructor would require significant code changes as it used lots of places that would then cause more change then more change as we go from int to long without casting because everything is in a loop in validate.

File: src/main/java/gov/nasa/pds/tools/util/ContextProductReference.java (hunk 1 above)
Comment (al-niessner) [reply src/main/java/gov/nasa/pds/tools/util/ContextProductReference.java]: Sure. I love to remove dead code. Done.

Comment (al-niessner) [reply src/main/java/gov/nasa/pds/tools/util/ContextProductReference.java]: I think Jordon already did.
