### PR TITLE
Code changes to support issue #238

### LINKED ISSUE #238: validate does not perform full bundle validation when using a specific bundle.xml
**Describe the bug**
When the `validate` tool is provided a target, which happens to be a specific `bundle.xml` file as opposed to a bundle directory, the tool fails to perform product-level validation for products referenced within the various collections pointed to by the `bundle.xml` file. 

**To Reproduce**
1. Download the bundle located at: https://pds-imaging.jpl.nasa.gov/data/nsyt/insight_cameras/ (NOTE: don't download the entire bundle, but instead look to replicate something similar in the regression test suite)
2. Validate the bundle by specifying the `bundle.xml`: `validate -R pds4.bundle -t insight_cameras/bundle.xml`
3. Notice the following output DOES NOT include any product-level checks:

```
$ validate -R pds4.bundle -t insight_cameras/bundle.xml 
PDS Validate Tool Report

Configuration:
   Version                       1.21.0
   Date                          2020-06-18T21:54:01Z

Parameters:
   Targets                       [file:/insight_cameras/bundle.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /validate/resources/registered_context_products.json



Product Level Validation Results

  PASS: file:/insight_cameras/bundle.xml

Summary:

  0 error(s)
  0 warning(s)


End of Report
Completed execution in 8203 ms
```

**Expected behavior**
1. Download the bundle located at: https://pds-imaging.jpl.nasa.gov/data/nsyt/insight_cameras/
2. Validate the bundle by specifying the `bundle.xml`: `validate -R pds4.bundle -t insight_cameras/bundle.xml`
3. Expected output should be similar to when calling validate by pointing to the enclosing directory of the bundle (i.e. same as `validate -R pds4.bundle -t insight_cameras/`)
   * NOTE: the output will differ because the insight_cameras directory has multiple `bundle*.xml` labels. the expected functionality expected here is validate will only validate the input `bundle*.xml` for bundle validation. it may validate other `bundle.xml` files in the base directory, but it will only perform bundle validation (integrity checking) on the bundle input and the associated collections that it references.

```
$ validate -R pds4.bundle -t insight_cameras/bundle.xml 
PDS Validate Tool Report

Configuration:
   Version                       1.21.0
   Date                          2020-06-18T21:54:01Z

Parameters:
   Targets                       [file:/insight_cameras/bundle.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /validate/resources/registered_context_products.json

Product Level Validation Results

  PASS: file:/insight_cameras/bundle.xml
..............................
  PASS: file:/insight_cameras/data/collection_data.xml
...
  PASS: file:/insight_cameras/data/sol/0212/mipl/edr/icc/C000M0212_615350914EDR_F0000_0461M2.xml
...
  PASS: file:/insight_cameras/data/sol/0212/mipl/rdr/icc/C000M0212_615350914CPG_F0000_0461M2.xml
...
  PASS: file:/insight_cameras/data/sol/0212/mipl/rdr/icc/C000M0212_615350914CSG_F0000_0461M2.xml
...
  PASS: file:/insight_cameras/data/sol/0212/mipl/rdr/icc/C000M0212_615350914DPG_F0000_0461M1.xml
...
  PASS: file:/insight_cameras/data/sol/0212/mipl/rdr/icc/C000M0212_615350914RZS_F0000_0461M1.xml
...
  PASS: file:/insight_cameras/data/sol/0212/mipl/rdr/icc/C000M0212_615350914ZPS_F0000_0461M1.xml

...
```

** Version of Software Used**
Version 1.21.0
Release Date: 2020-03-11 08:54:01
Core Schema: PDS4_PDS_1D00.xsd
Core Schematron: PDS4_PDS_1D00.sch

**Test Data / Additional context**
See: https://pds-imaging.jpl.nasa.gov/data/nsyt/insight_cameras/

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Red Hat Enterprise Linux Workstation release 7.3

**Applicable requirements**
n/a

### PR DESCRIPTION
**Pull request by qchaupds**
Pull request to close #238

Currently, validate module does not allow a pds4.bundle rule to apply to specific target which is a file.
The new logic is to allow the exception and also to only pick up the specific bundle target and only the latest collection file.
If a directory is specified for target, only the latest bundle and collection will be processed for product level validation.

The given test directory has multiple bundle and collection files.
```
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 201 % find src/test/resources/github238/valid -name "*.xml" | egrep "bundle|collection"
src/test/resources/github238/valid/bundle_kaguya_derived.xml
src/test/resources/github238/valid/bundle_kaguya_derived_2.xml
src/test/resources/github238/valid/bundle_kaguya_derived_3.xml
src/test/resources/github238/valid/bundle_kaguya_derived_4.xml
src/test/resources/github238/valid/bundle_kaguya_derived_5.xml
src/test/resources/github238/valid/bundle_kaguya_derived_6.xml
src/test/resources/github238/valid/bundle_kaguya_derived_7.xml
src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory.xml
src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_4.xml
src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_2.xml
src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_3.xml
src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_5.xml
```

Test 1: the target is a file

Expected result: only the specified bundle file is processed and only the latest collection file is processed.
```
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 146 % validate -R pds4.bundle --skip-content-validation -r target/test/report_github238_specified_file_10_27_2020.json -s json -t src/test/resources/github238/valid/bundle_kaguya_derived.xml >& t2; grep label target/test/report_github238_specified_file_10_27_2020.json
    "allowUnlabeledFiles": "false",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/bundle_kaguya_derived.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per1.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per2.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per3.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_5.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_5.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/bundle_kaguya_derived.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per1.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per2.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per3.xml",
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 147 %
```

Test 2: the target is a directory.
Expected result: only the latest bundle file is processed and only the latest collection file is processed.
```
validate -R pds4.bundle --skip-content-validation -r target/test/report_github238_specified_dir_10_27_2020.json -s json -t src/test/resources/github238/valid > & t1 ; grep label target/test/report_github238_specified_dir_10_27_2020.json

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 168 % grep label target/test/report_github238_specified_dir_10_27_2020.json
    "allowUnlabeledFiles": "false",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/bundle_kaguya_derived_7.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per1.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per2.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per3.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_5.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_5.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/bundle_kaguya_derived_7.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per1.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per2.xml",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per3.xml",
```
Extra: Running tests against Jordan's test input which has a few bundle and collection files:
```
 validate -R pds4.bundle --skip-content-validation -r report_github238_specified_file_10_27_2020_from_jordan.json -s json -t ~jpadams/sandbox/insight_cameras/bundle_5.0.xml >& t2
```

Expected result, only the specified bundle and latest collection file is processed for product validation.

```
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 152 % egrep -B 1 -A 4 "collection_|bundle_" report_github238_specified_file_10_27_2020_from_jordan.json
  "parameters": {
    "targets": "[file:/home/jpadams/sandbox/insight_cameras/bundle_5.0.xml]",
    "ruleType": "pds4.bundle",
    "severityLevel": "WARNING",
    "recurseDirectories": "true",
    "fileFiltersUsed": "[*.xml, *.XML]",
--
      "status": "PASS",
      "label": "file:/home/jpadams/sandbox/insight_cameras/bundle_5.0.xml",
      "messages": [],
      "fragments": [],
      "dataContents": []
    },
--
      "status": "PASS",
      "label": "file:/home/jpadams/sandbox/insight_cameras/data/collection_data_6.0.xml",
      "messages": [],
      "fragments": [],
      "dataContents": []
    },
--
```

```
 validate -R pds4.bundle --skip-content-validation -r report_github238_specified_dir_10_27_2020_from_jordan.json -s json -t ~jpadams/sandbox/insight_cameras/ >& t1
```

Expected result, only the latest bundle (bundle_6.0.xml) and latest collection file (collection_data_6.0.xml) are processed for product validation.

```
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 151 %  egrep -B 1 -A 4 "collection_|bundle_" report_github238_specified_dir_10_27_2020_from_jordan.json
      "status": "PASS",
      "label": "file:/home/jpadams/sandbox/insight_cameras/bundle_6.0.xml",
      "messages": [],
      "fragments": [],
      "dataContents": []
    },
--
      "status": "PASS",
      "label": "file:/home/jpadams/sandbox/insight_cameras/data/collection_data_6.0.xml",
      "messages": [],
      "fragments": [],
      "dataContents": []
    },
```

### CODE REVIEW

File: src/main/java/gov/nasa/pds/tools/util/LidVid.java [hunk 1]
```diff
@@ -0,0 +1,164 @@
...
+                ("Product_Bundle".    equals(extractor.getValueFromDoc(PRODUCT_CLASS))))  {
+              String lid = extractor.getValueFromDoc(LOGICAL_IDENTIFIER);
+              String vid = extractor.getValueFromDoc(VERSION_ID);
+              lidsList.add(lid);
+              vidsList.add(vid);
+              vidsTable.put(vid,child);
+            }
+          } catch (Exception e) {
+            //Ignore. This isn't a valid Bundle/Collection label so skip it.
+            System.out.println("reduceToLatestTargetOnly: Skipping " + child.getUrl());
```
Comment (jordanpadams) [inline src/main/java/gov/nasa/pds/tools/util/LidVid.java]: @qchaupds can we make this a debug or INFO message? this shows up in all user outputs and can mess up pipelines that try to read the JSON output from the report.

File: src/main/java/gov/nasa/pds/tools/label/LocationValidator.java [hunk 2]
```diff
@@ -158,9 +216,17 @@ public void validate(ValidateProblemHandler problemHandler, URL url) {
 			task.setRule(rule);
 			task.setRuleManager(ruleManager);
 			Crawler crawler = CrawlerFactory.newInstance(url);
+            // Set filter so the crawler will ignore other bundle/collection files that are not latest.
+            crawler.addAllIgnoreItems(ignoreList);
+            System.out.println("LocationValidator:validate:location,rule.isApplicable " + location + " " + rule.isApplicable(location));
+            System.out.println("LocationValidator:validate:ignoreList.size() " + Integer.toString(ignoreList.size()));
```
Comment (jordanpadams) [inline src/main/java/gov/nasa/pds/tools/label/LocationValidator.java]: @qchaupds similar to other comment, can we make these debug logs?

**Comment by jordanpadams** [comment]
@qchaupds i updated your test suite to be more ops-like. technically, every the relationship between PDS4 XML label and product file must be one-to-one. the previous example had many collection labels pointing to the same inventory file product, which is illegal. we actually have a ticket coming up in this build to address this issue as well: #245

i also updated some of the bundles to reference collections by lidvid, so we can

bundle1 -> collection1 ->product1
bundle2 -> collection2 ->product1,2
bundle3 -> collection3 ->product1,2,3
bundle4 -> collection4 ->product1,2,3,4
bundle5 -> collection5 ->product1,2,3,4,5
bundle6 (reference by LID, get latest) -> collection5 ->product1,2,3,4,5
bundle7 (reference by LID, get latest) -> collection5 ->product1,2,3,4,5

here is what happened when i ran it against bundle1:

```
$ validate-1.25.0-SNAPSHOT/bin/validate -R pds4.bundle --skip-content-validation -t src/test/resources/github238/valid/bundle_kaguya_derived.xml
LocationValidator:validate:location,rule.isApplicable file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/ true
LocationValidator:validate:ignoreList.size() 10

PDS Validate Tool Report

Configuration:
   Version                       1.25.0-SNAPSHOT
   Date                          2020-10-30T04:22:52Z

Parameters:
   Targets                       [file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/bundle_kaguya_derived.xml]
   Rule Type                     pds4.bundle
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       off
   Product Level Validation      on
   Allow Unlabeled Files         false
   Max Errors                    100000
   Registered Contexts File      /Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/validate-1.25.0-SNAPSHOT/resources/registered_context_products.json



Product Level Validation Results

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/bundle_kaguya_derived.xml
        1 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per5.xml
        2 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per4.xml
        3 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per1.xml
        4 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per3.xml
        5 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per2.xml
        6 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_5.xml
        7 product validation(s) completed


PDS4 Bundle Level Validation Results

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_5.xml
      WARNING  [warning.integrity.unreferenced_member]   Identifier 'urn:nasa:pds:kaguya_grs_spectra:data_spectra::1.5' is not a member of any collection within the given target
        1 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory.csv
      WARNING  [warning.file.not_referenced_in_label]   File is not referenced by any label
        2 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_2.csv
      WARNING  [warning.file.not_referenced_in_label]   File is not referenced by any label
        3 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_3.csv
      WARNING  [warning.file.not_referenced_in_label]   File is not referenced by any label
        4 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_4.csv
      WARNING  [warning.file.not_referenced_in_label]   File is not referenced by any label
        5 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/bundle_kaguya_derived.xml
      WARNING  [warning.integrity.member_not_found]   The member 'urn:nasa:pds:kaguya_grs_spectra:data_spectra::1.0' could not be found in any product within the given target.
        6 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per1.xml
        7 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per2.xml
        8 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per3.xml
        9 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per4.xml
        10 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per5.xml
        11 integrity check(s) completed

Summary:

  0 error(s)
  6 warning(s)

  Product Validation Summary:
    7          product(s) passed
    0          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    11         check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    4            warning.file.not_referenced_in_label
    1            warning.integrity.member_not_found
    1            warning.integrity.unreferenced_member

End of Report
Completed execution in 4483 ms
```

a few issues here:

1. 
```
file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory.csv
      WARNING  [warning.file.not_referenced_in_label]   File is not referenced by any label
        2 integrity check(s) completed
```

this CSV is actually referenced by `spectra_data_collection_inventory.xml`, so this error should not be thrown. additionally, from the looks of this, it would appear it is still validating the latest version of the collection in the bundle, but in this case, the bundle explicitly references by LIDVID and should be using version 1 of the collection.

2.
```
  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/bundle_kaguya_derived.xml
      WARNING  [warning.integrity.member_not_found]   The member 'urn:nasa:pds:kaguya_grs_spectra:data_spectra::1.0' could not be found in any product within the given target.
        6 integrity check(s) completed
```
not sure what is happening here either. this bundle LID is inherently referenced since that the bundle we are validating against. something funky may be going on here with the data structure you are using to determine how to perform the integrity checks.

File: src/main/java/gov/nasa/pds/tools/label/LocationValidator.java (hunk 2 above)
Comment (qchaupds) [reply src/main/java/gov/nasa/pds/tools/label/LocationValidator.java]: All the println statements that have been introduced in this commit have been changed to debug or removed.  A quick run of both targets as file and directory verified that no extraneous printout end up in the output.

File: src/main/java/gov/nasa/pds/tools/util/LidVid.java (hunk 1 above)
Comment (qchaupds) [reply src/main/java/gov/nasa/pds/tools/util/LidVid.java]: Yes, they have been changed.  Will be ready for next commit.

File: src/main/java/gov/nasa/pds/tools/label/LocationValidator.java (hunk 2 above)
Comment (qchaupds) [reply src/main/java/gov/nasa/pds/tools/label/LocationValidator.java]: The code changes have been checked in for your second review @jordanpadams .
A separate email have been sent to give more details.

**Comment by jordanpadams** [comment]
@qchaupds the updates look great! we are almost there. one final use case we need to handle:

bundle references a collection by LID - validate should use the latest version of the collection only to perform validation

testing with `bundle_kaguya_derived_6.xml`, this references the collection by LID:
```
$ validate-1.25.0-SNAPSHOT/bin/validate -R pds4.bundle --skip-content-validation -t src/test/resources/github238/valid/bundle_kaguya_derived_6.xml

PDS Validate Tool Report

Configuration:
   Version                       1.25.0-SNAPSHOT
   Date                          2020-11-04T02:51:35Z

Parameters:
   Targets                       [file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/bundle_kaguya_derived_6.xml]
   Rule Type                     pds4.bundle
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       off
   Product Level Validation      on
   Allow Unlabeled Files         false
   Max Errors                    100000
   Registered Contexts File      /Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/validate-1.25.0-SNAPSHOT/resources/registered_context_products.json



Product Level Validation Results

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/bundle_kaguya_derived_6.xml
        1 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per5.xml
        2 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per4.xml
        3 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per1.xml
        4 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory.xml
        5 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per3.xml
        6 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per2.xml
        7 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_3.xml
        8 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_2.xml
        9 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_5.xml
        10 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_4.xml
        11 product validation(s) completed


PDS4 Bundle Level Validation Results

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory.xml
        1 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_3.xml
        2 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_2.xml
        3 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_5.xml
        4 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_4.xml
        5 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/bundle_kaguya_derived_6.xml
        6 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per1.xml
        7 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per2.xml
        8 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per3.xml
        9 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per4.xml
        10 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per5.xml
        11 integrity check(s) completed

Summary:

  0 error(s)
  0 warning(s)

  Product Validation Summary:
    11         product(s) passed
    0          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    11         check(s) passed
    0          check(s) failed
    0          check(s) skipped


End of Report
Completed execution in 4143 ms
```

I would imagine the output should match the output if you test with `bundle_kaguya_derived_7.xml`, because even though `bundle_kaguya_derived_6.xml` only references by LID, it is notionally referencing the same collection as `bundle_kaguya_derived_7.xml` (the latest collection.

```
$ validate-1.25.0-SNAPSHOT/bin/validate -R pds4.bundle --skip-content-validation -t src/test/resources/github238/valid/bundle_kaguya_derived_7.xml

PDS Validate Tool Report

Configuration:
   Version                       1.25.0-SNAPSHOT
   Date                          2020-11-04T02:57:03Z

Parameters:
   Targets                       [file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/bundle_kaguya_derived_7.xml]
   Rule Type                     pds4.bundle
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       off
   Product Level Validation      on
   Allow Unlabeled Files         false
   Max Errors                    100000
   Registered Contexts File      /Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/validate-1.25.0-SNAPSHOT/resources/registered_context_products.json



Product Level Validation Results

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/bundle_kaguya_derived_7.xml
        1 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per5.xml
        2 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per4.xml
        3 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per1.xml
        4 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per3.xml
        5 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per2.xml
        6 product validation(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_5.xml
        7 product validation(s) completed


PDS4 Bundle Level Validation Results

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_5.xml
        1 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory.csv
      WARNING  [warning.file.not_referenced_in_label]   File is not referenced by any label
        2 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_2.csv
      WARNING  [warning.file.not_referenced_in_label]   File is not referenced by any label
        3 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_3.csv
      WARNING  [warning.file.not_referenced_in_label]   File is not referenced by any label
        4 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/spectra_data_collection_inventory_4.csv
      WARNING  [warning.file.not_referenced_in_label]   File is not referenced by any label
        5 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/bundle_kaguya_derived_7.xml
        6 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per1.xml
        7 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per2.xml
        8 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per3.xml
        9 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per4.xml
        10 integrity check(s) completed

  PASS: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github238/valid/data_spectra/kgrs_calibrated_spectra_per5.xml
        11 integrity check(s) completed

Summary:

  0 error(s)
  4 warning(s)

  Product Validation Summary:
    7          product(s) passed
    0          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    11         check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    4            warning.file.not_referenced_in_label

End of Report
Completed execution in 3897 ms
```

Isn't PDS4 validation fun? :-)

**Comment by jordanpadams** [comment]
@qchaupds also, per the logic you have added into validate, can we make sure output a log.info message in the event when we find multiple bundles and decide to only validate the latest version? i think this functionality makes sense, but I want to make sure it is at least output in the log message if that is possible.

File: src/main/java/gov/nasa/pds/tools/label/LocationValidator.java (hunk 2 above)
Comment (qchaupds) [reply src/main/java/gov/nasa/pds/tools/label/LocationValidator.java]: Your comments from last night has been responded to via code commit.

**Review by jordanpadams — APPROVED** [review]
🎉
