### PR TITLE
Provide enhanced exception logging for Array validation per #566

### LINKED ISSUE #567: Update ArrayObject exceptions to enable improved error messaging
> Asking the user to look at data type vs size is not going to go over well in the end. The checks in ArrayObject that check dimensions and index can return different (less generic) exceptions to produce a meaningful message appropriate the actual failure. If the reference to data type is data type size vs number of total bytes available then that should be simple to check as well given actual type is returned by ArrayObject.

@al-niessner totally agree. will create a separate ticket to refactor ArrayObject to provide better context to the user.

_Originally posted by @jordanpadams in https://github.com/NASA-PDS/validate/issues/566#issuecomment-1335669433_

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Treat the various purposely thrown exceptions independently to improve the messaging. Still generates a similar error causing the same problem report but different messages. While not exhaustive, put more text in message to report the generic messages to fix the original throw to put the cause in the exception as a message.
 
## ⚙️ Test Data and/or Report
See unit tests of this PR

## ♻️ Related Issues
Closes #567

### CODE REVIEW

File: src/main/java/gov/nasa/pds/tools/validate/content/array/ArrayContentValidator.java [hunk 1]
```diff
@@ -252,6 +252,16 @@ private void validatePosition(Array array, ArrayObject arrayObject, ArrayLocatio
           LOG.warn("validatePosition:Unhandled dataType {}", dataType);
           break;
       }
+    } catch (ArrayIndexOutOfBoundsException aiobe) {
+      String message = "No message specified, but probably index out of range. Report this message to have it fixed (have original exception given a message";
```
Comment (nutjob4life) [inline src/main/java/gov/nasa/pds/tools/validate/content/array/ArrayContentValidator.java]: Extreme pedant here: closing `)` to match the `(` surrounding `have original exception given a message`.

File: src/main/java/gov/nasa/pds/tools/validate/content/array/ArrayContentValidator.java [hunk 2]
```diff
@@ -252,6 +252,16 @@ private void validatePosition(Array array, ArrayObject arrayObject, ArrayLocatio
...
+      if (aiobe.getMessage() != null)
+        message = aiobe.getMessage();
+      throw new IOException(message);
+    } catch (IllegalArgumentException iae) {
+      String message = "No message specified, but probably wrong number of dimensions. Report this message to have it fixed (have original exception given a message";
```
Comment (nutjob4life) [inline src/main/java/gov/nasa/pds/tools/validate/content/array/ArrayContentValidator.java]: Ditto. (Extreme pedants are the worst! 😆)

**Review by nutjob4life — COMMENTED** [review]
This is fine; don't worry about the `)` … I'm just being annoying 😝

**Review by nutjob4life — APPROVED** [review]

File: src/main/java/gov/nasa/pds/tools/validate/content/array/ArrayContentValidator.java (hunk 1 above)
Comment (al-niessner) [reply src/main/java/gov/nasa/pds/tools/validate/content/array/ArrayContentValidator.java]: fixed

File: src/main/java/gov/nasa/pds/tools/validate/content/array/ArrayContentValidator.java (hunk 2 above)
Comment (al-niessner) [reply src/main/java/gov/nasa/pds/tools/validate/content/array/ArrayContentValidator.java]: fixed

**Review by nutjob4life — APPROVED** [review]
This makes me so happy :)))))))))))))
