### PR TITLE
Resolve #548

### LINKED ISSUE #548: Validate fails regression test on issue 303
## 🐛 Describe the bug identified during I&T
Regression test [validate#303](https://github.com/NASA-PDS/validate/issues/303) fails in the regression testing tool. 

**Posted here for discussion or to address root cause.** It appears that test data is no longer valid for the validate tool. Perhaps the tool evolved to report different information regarding the data set that were unrecognized at the time the issue was originally created. 

Data set originally identified a problematic `array 1` and now specifies `array 0` My guess is it went from reporting human counting to code counting. 

Then it fails validation and provides no further detail. For instance, the following is expected, but missing:   
```
WARNING  [error.label.filesize_mismatch] ... Object-defined size+offset is greater than actual file size in data file: 4240384 > 4219200
```
It's not clear if the algorithm changed and the analysis is no longer conducted or whether the process terminated earlier. It's also possible the data set isn't clean and needs to be revisited for this test. 

## 🥼 Related Test Case(s)
B12.0, VAL.9

## 🔁 : Related issues
https://github.com/NASA-PDS/validate/issues/303

---

## ➕ Additional Details
https://pds-jenkins.jpl.nasa.gov/job/console-regression-tests/job/develop/298/console
https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/4058182

### 📜 To Reproduce
See steps [here](https://pds-jenkins.jpl.nasa.gov/job/console-regression-tests/job/develop/298/console).

### 🕵️ Expected behavior
Test passes all stages successfully.

### 📚 Version of Software Used
Validate 3.0.2

### 🩺 Test Data / Additional context
Test data located at https://github.com/NASA-PDS/validate/tree/main/src/test/resources/github303

### 🖥 System Info
 - OS: Mac OS X 11.7.1 or Ubuntu-latest (Dockerized)
 - java 11.0.3 2019-04-16 LTS
 - Validate 2.4.0 or 3.0.0
 - GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
 
---

### PR DESCRIPTION
**Pull request by nutjob4life**
## 🗒️ Summary

Merge this to resolve #548 by addressing two specific points made:

- Error reporting went from human-centric (1-based) to computer-centric (0-based) in recent changes; this puts it back to 1-based.
- A detail message changed to `null`; we can't put that back as the [calculation is no longer done and didn't make sense](https://github.com/NASA-PDS/validate/issues/548#issuecomment-1312860355); this at least removes the useless `null` detail message.

## ⚙️ Test Data and/or Report

```
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
```
Quite some time later
```
[INFO] Tests run: 160, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 257.202 s - in cucumber.CucumberTest
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 161, Failures: 0, Errors: 0, Skipped: 1
```

## ♻️ Related Issues

- #548

### CODE REVIEW

File: src/main/java/gov/nasa/pds/tools/validate/content/array/ArrayContentValidator.java [hunk 1]
```diff
@@ -259,8 +259,14 @@ private void validatePosition(Array array, ArrayObject arrayObject, ArrayLocatio
         loc = loc.replaceAll("\\[", "");
         loc = loc.replaceAll("\\]", "");
       }
-      throw new IOException("Error occurred while trying to " + "read data at location " + loc
-          + ": " + ee.getMessage());
+
+      // #544: @jpl-jengelke reports that validate used to produce a detailed error message but now just
+      // says `null`. @jordanpadams says the calculation is no longer completed by the software and didn't
+      // make sense, but that said, `null` is not intuitive.
+      String message = "Error occurred while trying to " + "read data at location " + loc + ". Verify possible mismatch in file size and expected array size.";
```
Comment (jordanpadams) [inline src/main/java/gov/nasa/pds/tools/validate/content/array/ArrayContentValidator.java:266]: @nutjob4life @jpl-jengelke made a slight tweak. how do it look?

**Review by jpl-jengelke — APPROVED** [review]
Looks good to me. Thanks!

File: src/main/java/gov/nasa/pds/tools/validate/content/array/ArrayContentValidator.java (hunk 1 above)
Comment (nutjob4life) [reply src/main/java/gov/nasa/pds/tools/validate/content/array/ArrayContentValidator.java:266]: That looks fantastic @jordanpadams !

**Review by jordanpadams — APPROVED** [review]
